-- General
var DASHBOARD_PERSIST_DATA = "D:\Dashboard\Data"
var DASHBOARD_OWNER_ALERT_DIST = "olga.gorlova@intel.com, kimberly.j.dejong@intel.com, noah.mcdaniel@intel.com"
-- Monitor Email
var PCAM_MONITOR_EMAIL = "ltd.automation.ait@intel.com, td.ata.pla.operations.pfi@intel.com"
var PCAM_DCT_MONITOR_EMAIL = ""
var ONCALL_SUPPORT_EMAIL = "td.ata.pla.operations.pfi@intel.com"
var CUDESEG_MONITOR_EMAIL = "ltd.automation.ait@intel.com"
var CUDESEG_MONITOR_WITH_USER_EMAIL = "ltd.automation.ait@intel.com, mark.phillips@intel.com"
var E3_MONITOR_EMAIL = "kimberly.j.dejong@intel.com, wenjie1.jiang@intel.com, robyn.meinhard@intel.com, amy.zbylut@intel.com"
var E3_ADDL_CONTACT_EMAIL = "theodore.stevenson@intel.com"
var E3DEV_MONITOR_EMAIL = "ben.az.jones@intel.com, sharon.quan@intel.com, wenjie1.jiang@intel.com, amy.zbylut@intel.com, kimberly.j.dejong@intel.com"
var E3_VF_STATS_MONITOR_EMAIL = "chris.sluder@intel.com"
var PCDSLURRYMATRIX_EMAIL = "d1.fe.cmp.eng@intel.com, PTDBECMPEngineering@intel.com, d1dregen_ple@intel.com, D1DR_PRT@intel.com, ptd.tyche.bsp.tbt@intel.com, ptd.cmp.iq@intel.com, david.clarkson@intel.com, olga.gorlova@intel.com"
var SC_MONITOR_EMAIL = "LTDAutomationStationControllers@intel.com, td.ata.pla.operations.pfi@intel.com, gregory.r.lester@intel.com, olga.gorlova@intel.com, david.clarkson@intel.com, kimberly.j.dejong@intel.com"
var SPC_MONITOR_EMAIL = "olga.gorlova@intel.com, josephine.moran@intel.com, david.clarkson@intel.com"
var WIP_MONITOR_EMAIL = "ltd.automation.ait@intel.com"
var DIP_VAT_EMAIL="NA"
var ETCH_VAT_EMAIL="NA"
var LITHO_VAT_EMAIL="NA"
var SORT_C4_VAT_EMAIL="NA"
var TMC_VAT_EMAIL="NA"
var PAGING_LIST = "RF3_PFI_DM"
-- Barnum
var BARNUM_CATALOG = "Barnum"
var BARNUM_DOMAIN1 = "AIT"
var BARNUM_DOMAIN2 = "SPC"
var BARNUM_FACILITY = "D1D"
var BARNUM_LINK = "http://rf3-auto.rf3prod.mfg.intel.com/Barnum/default.asp?do=display&fab=D1D&grp=AIT&id="
var BARNUM_SQL_NODE = "rf3pdb115misql.rf3prod.mfg.intel.com\SQL05"
var BARNUM_RESOURCE_PENDING_FIRST_NAME = "Resource Pending"
var BARNUM_CONV = "Conversion - Process, Conversion - Contaminent"
var BARNUM_DEMO = "Demo - Multiple Tools, Demo - Single Tool"
var BARNUM_INSTALL = "Install - First of a Kind, Install - Second of a Kind, Install - Virtual Winclient, Tool - New Install"
var BARNUM_RELO = "Relocation - Bay, Relocation - Building/Site"
-- BarnumSN
var BARNUMSN_CATALOG = "HelpDesk_30000"
var BARNUMSN_LINK = "http://rf3pvxsn01.rf3prod.mfg.intel.com:8081/nav_to.do?uri=u_barnum_request.do?sys_id="
var BARNUMSN_SQL_NODE = "rf3pdb314sn.rf3prod.mfg.intel.com"
var BARNUMSN_TABLE = "d1d_ait_barnum_ticket_summary"
var BARNUMSN_TABLE_D1C = "d1c_ait_barnum_ticket_summary"
var D1DSRFILEFILTER = "@{DASHBOARD_PERSIST_DATA}\PCAM\Output\1_BarnumSN_Metrics_Data.csv"
var VFSRFILEFILTER = "@{DASHBOARD_PERSIST_DATA}\PCAM\Output\ISMP_Request_Query_All.htm"
var REQUEST_NAME = "BarnumSN"
var SRSITE = "%{D1DSR_CSV}"
-- E3
var LOCALE3DATASOURCE = "D1D_PROD_E3"
var COLLECTION_EXCLUDE = ""
var COLLECTION_INCLUDE = "P1272%_CE_%, P1273%_CE_%, P1274%_CE_%, P1275%_CE_%"
var E3_GOLDTOOL_MOVED_INCLUDE = "%_CE_%, %FBE%"
var SDK_INSTANCE_EXCLUDE = "DEMO*"
-- FSUI
var FSUISQLID = "FSUIHistoryReader"
var FSUISQLPW = "FSUIHR_mxAo9Ghz"
var FSUISQLNODE = "rf3pDB416SQL01\sql01"
-- ISMP
var ISMP_SQL_NODE="CCEPDB706I01.cdcprod.mfg.intel.com"
var ISMP_CATALOG="IsmpData"
var SR_SITES = "F11x%,F32%,F24%,F28%,ATT%"
-- MCCB
var MCCBSITE = "D1C"
var MCCBSITE2 = "None"
var MCCBSITEFILTER = "D1C, F24, F28, OSA"
var MCCBCHANGE = "D1CChange"
var MCCBCOMPLETEDBY = "D1CCompletedBy"
var MCCBCOMPLETEDON = "D1CCompletedOn"
var MCCBCOMMENT = "[D1C Local Comments]"
var MCCBDAYS = "D1CDaysToDone"
var MCCBSENDINGSITE = "D1C"
var MCCBAREAEXCLUDE = "NA"
var MCCBPROCESSEXCLUDE = ""
var SUPPORTSITEVIEW = "D1C"
var AFOMCCBSTATUS = "Not Supported"
var D1CMCCBSTATUS = "Active%, Pending%, ActiveHold%, Proliferation%"
var D1DMCCBSTATUS = "Not Supported"
var F11xMCCBSTATUS = "Not Supported"
var F24MCCBSTATUS = "Not Supported"
var F28MCCBSTATUS = "Not Supported"
var F68MCCBSTATUS = "Not Supported"
var OSAMCCBSTATUS = "Not Supported"
var SUPPORTSITEVIEWC4SORT = "D1C"
var AFOC4SORTMCCBSTATUS = "Not Supported"
var D1CC4SORTMCCBSTATUS = "Active%, Pending%, ActiveHold%, Proliferation%"
var D1DC4SORTMCCBSTATUS = "Not Supported"
var F11xC4SORTMCCBSTATUS = "Not Supported"
var F24C4SORTMCCBSTATUS = "Not Supported"
var F28C4SORTMCCBSTATUS = "Not Supported"
var F68C4SORTMCCBSTATUS = "Not Supported"
var OSAC4SORTMCCBSTATUS = "Not Supported"
var D1CTIPRFILEFILTER = "@{DASHBOARD_PERSIST_DATA}\PCAM\Output\TIPR_Query_Install.csv"
var D1DTIPRFILEFILTER = "@{DASHBOARD_PERSIST_DATA}\PCAM\Output\1_TIPR_Query_Install_Data.csv"
var F24TIPRFILEFILTER = "D:\Dashboard\Data\PCAM\TIPR_Metrics_PAS.htm"
var F32TIPRFILEFILTER = "D:\Dashboard\Web\PFI\Output\TIPR_Metrics_PAS.htm"
var DEFMETFSGAREA = "Defect Metro, Fab Support Group, DefMet, FSG, DefectMetro, DM, WH"
var DIFFIMPAREA = "Diffusion, Implant, EPI, DI, IM"
var ETCHAREA = "Etch%, ET, Etch - Dry, Etch - Wet"
var LITHOAREA = "Litho, Lithography, LI"
var PLANARAREA = "Inline - ETEST, Planar, PL"
var TFAREA = "EqpMetro, ThinFilms, TFMet, Thin Films%, TF, TM"
var C4SORTAREA = "C4, Sort, ST"
var WIPAREA = "ASOM%, WIP"
var TIPRSITE = "%{D1D_CSV}"
-- MES300
var FAB300_APP_NODES = "*ap357n*, *ap657n*"
var MAO_FACILITY = "RA3"
var LOCALMARSDATASOURCE = "D1D_PROD_MARS"
var VFGOLDMARSDATASOURCE = "D1D_PROD_MARS"
var LOCALXEUSDATASOURCE = "D1D_PROD_XEUS"
var MES300_ENTITY_EXCLUDE = "AIT*, LTDSORTTESTECP, HMEPM*, RIOL*, RPTC*, RPU*, RPV*, TAF*, ReelLotIdSemaphore, PLB_HEAD*, HEAD*, PCHD*, *PLPUMP*, *MONGO*, ZZ*, LPM*, OVP*, PRG*, OVI*, OVN*, SBT*, CAM*, VFQ*, AFQ*, AFW*, ARM*, BAG*, DAT*, DFW*, FMT*, NANO*, RIN*, RIT*, SNK*, VFH*, TDR*, LSB456, LBRD*, MBCM*, MBNW*, UFP*, VBG*, DOR9*, LAMP*,SC1*,SC2*,SC4*,SC5*,SC6*,SC7*,SC8*,TRIK*,SMCU*,SMCA*,SMCB*,SMCC*,*DUMMY*,OVM*"
var MES300_EQUIPGROUP_ENTITY_EXCLUDE = "N/A"
var MES300_CUFLAG_ENTITY_EXCLUDE = "*HEAD*, NANO*, PCHD*, *PUMP*, STCX*, RIOL*"
var MES300_RTS_ENTITY_EXCLUDE = "UTX*, SPV5*, SAJ446, SAY434, SAY436, SAY437, SAY438"
var MES300_PROCESS_INCLUDE = "*"
var MES300_ENTITY_TYPE_EXCLUDE = "FOUPBox,MotherBoard,ProbeCard,ReticlePod,StorageMachine,TestHead"
var MES300_FA_EXCLUDE = "Automation, AFO*, Bulk Chemical Delivery, C4, FBE, OTHER, LIWS, PC, DieSort, DiePrep, Reticle, SubFab, Class, WaferLevelAssembly"
var MES300_SITE_EXCLUDE = "AAL,AFO,DPD,ODS,ST4,STT,WATD"
var MES300_CUDESEG_ENTITY_EXCLUDE = "ASOMMOQ, DDUM*,DOR*,LPM*,STC002*,STCX*,UVS*,VDUM*,ZBS90*,ZDK90*,ZDK90,ZED90*,ZSK90,ZAB90*,ZSZ91*,ZTM91*,ZVP91*,ZMG91*,ZCP90*,ZAL90*,ZME90*,ZTE90*, ZBU90*,ZRO90*,ZEB90*,CDK90*,MIK92*,ZTE91*,PRG*"
var MES300_CUDESEG_FA_EXCLUDE = "Automation,C4,FBE,RP1*"
var CUDESEG_SOFTPINIGNORETOOLS = "DRT*, PRT*"
var CUDESEG_OPER_EXCLUDE = "2521"
var PURGE_CONTACT = "Donavon Miller and Integration"
var PURGE_EXCLUDE_PROCESS = "121%, 126%, XXRP%, RP%"
var MES300_SITE_SPECIFIC_QUERY = "(Site like '${SITE1}' and (NOT IsInList(EquipLocation, '${SITE1_BAY}'))) OR (Site like '${SITE2}' and (NOT IsInList(EquipLocation, '${SITE2_BAY}'))) OR (Site like 'RB1' and (NOT IsInList(EquipLocation, 'STRING, 2, 5, 6, 8, 10, 11, 12, 14')))"
var MES300_SITE1 = "D1X"
var MES300_SITE1_BAY = "600W,600E,601W,601E,602W,602E,603W,603E,604W,604E,605W,605E,606,606A,606B,606C,607W,607E,608W,608E,609W,609E,609A,609B,609C,610W,610E,611W,611E,612E,612W,613A,613B,613W,613E,614W,614E,615W,615E,616E,616W,400W,400E,400B,400AW,400AE,401W,401E,402W,402E,403W,403E,404A,404B,404C,405W,405E,407A,407B,407W,407E,408W,408E,409W,409E,410A,410B,410E,410W,411E,411W,412E,412W,413E,413W"
var MES300_SITE2 = "D1D"
var MES300_SITE2_BAY = "2,2A,2B,ADL,100,101,101E,102,102E,103,104,104E,106,108,109,109A,109E,110,111,112,112E,113,113E,114,115,116,116A,116E,117,200,201,201A,202,203,203A,204,204E,204EW,207,208,209,209A,210,210E,211,211A,212,212E,213,213E,214,215,215E,216,217"
var OWD_EXCLUDE_LIST = "4767, 6615, 9681, 9683, 119116, 119117, 119222, 119223, 121628, 121629, 121630, 121631, 122502, 122503, 119375, 119376, 119368, 115815, 115817, 115819, 115821, 122141, 122142, 122143, 122144, 122149, 122150, 122151, 122152, 122153, 125582"
var OWD_PROCESS_EXCLUDE_LIST = "1264.0, 1266.0, 1268.0, 1269.0"
var MES300_AVL_SITE = "D1D"
var MES300_AVL_VL = "D1D"
var MES300_AVL_OB = "D1D"
var MES300_STOCKER_EXCLUDE = "C4, SPX*, AMHSD1DD1CLink, ETestSortDestLock, SegmentLock"
var MES300_PCD_EXCLUDE = "PLB_HEAD*,PLB401_HEAD*,PLB402_HEAD*,PLB404_HEAD*,DRT*_LP*"
var MES300_PCD_INCLUDE = "PLM*,PLB*,PLI*,PLH*,PLE*,PRT*,DRT*,BSP*,PLR*"
var MES300_PCD_EXCLUDE_CEID = "DRTnb,DRTcb,PRTnb,PRTcb,BSPct"
var MES300_CORE_STATE_MODEL_EXCLUDE = "EquipmentNGPolishHead*,EquipmentChiller;*,EquipmentCSNHost*"
-- SC
var POST = "U"
var TOOLPOST = "H"
var NTSCCCServer = "\\rf3pvwb404n1\NTSCWebLog\ScCentralConfigLog*.xml, \\rf3pvwb404n2\NTSCWebLog\ScCentralConfigLog*.xml"
var NTSCCCHistoryExcludeList = "(AFP%, (FBE%, (C4%, (ASP%"
var SCNETSQLID = "uber"
var SCNETSQLPW = "h6wRu5Up"
var SCNETSQLNODE = "RF3PDB429SQL01\SQL01"
var WINCLIENT_EXCLUDE_LIST = "*AIT*,R2PCC*,R2PHPCC*,R3PCMDC*,R4PCCC*,RA4CMD*"
var WINCLIENT_NODE_LIST = "R*P*U, RA4*U"
var WINCLIENT_REBOOT_EXCLUDE = "RF3PXPYASMURLN3, *WXP*, *WINC*, RF3PAPMURL, *M, *EPX02*"
var DCSLOTCONFIG_LIST = "*CAR*, *OXS*, *OXT*"
var DCSLOTCONFIG_EXCLUDE_LIST = "*OXS427*"
var MAXCHAMBERDISCONNECT_LIST = "*GST*, *EST*, *NST*, *SST*, *KST*, *QST*"
var MAXCHAMBERDISCONNECT_EXCLUDE_LIST = "None"
var PLASMACLEAN_LIST = "*HME*"
var PLASMACLEAN_EXCLUDE_LIST = "*HME21*"
var TOOLDATA_LIST = "*CVD*,*LKL*,*WDP*"
var TOOLDATA_EXCLUDE_LIST = "None"
var WAFERCOUNTER_LIST = "*SLM*,*SLP*"
var WAFERCOUNTER_EXCLUDE_LIST = "None"
var HSMS_EXCLUDE_LIST = "DOR,TEN,AGN,CMT,CME,ETT,KNT,PWS,WPC,PMM,AGX,PFT"
var HSMS_IP_FILTER = "10[.]"
var YAS_NODELIST_EXCLUDE_LIST = "*SRA*"
var VALIDYASPATH = "\\\\rf3p-nas3-yas76.rf3prod.mfg.intel.com\\yas_mount76_out\\apps\\autoload\\sfiles,\\\\rf3p-nas-yas.rf3prod.mfg.intel.com\\yas_mount74_out\\apps\\autoload\\sfiles,\\\\rf3p-nas-yas72.rf3prod.mfg.intel.com\\yas_mount72_out\\apps\\autoload\\sfiles,\\\\rf2p-nas-yas-tool.rf2prod.mfg.intel.com\\yas_mount70_out\\apps\\autoload\\sfiles"
-- SPC#
var SPC_AREA_EXCLUDE_LIST = "FBE,Automation,Die Prep,Die Sort,Manufacturing,Z_Training"
var SPC_PROCESS_EXCLUDE_LIST = "1270, 1271"
var PILOT_MONITOR_EXCLUDE_LIST = "REG.DYN_ALTREG_EUV.74.MON"
-- TIPR
var Fab1 = "D1D"
var Fab1Pre = "R3P"
var Fab2Pre = "R4P"
var TIPRID = "TIPR_Read"
var TIPRPW = "glmGvtCPV$D"
var TIPRSQLNODE = "RF3PDB428SQL03\SQL03"
var D1D_TIPR_LINK = "http://rf3-auto.rf3prod.mfg.intel.com/tipr/AIT.asp?FA=All&EntityType=All&Entity="
var F24_TIPR_LINK = "http://f24-auto.f24prod.mfg.intel.com/tipr/AIT.asp?FA=All&EntityType=All&Entity="
var F32_TIPR_LINK = "http://f32-auto.f32prod.mfg.intel.com/tipr/AIT.asp?FA=All&EntityType=All&Entity="
var TIPR_BUILDING_EXCLUDE = "NA"
var TIPR_ENTITY_EXCLUDE = "NA"
var TIPRPROCESS = "%"
var EXCLUDETYPE = "NA"
var INCLUDETYPE = "Install"
var TIPR_WSTIE = "WSTie"
-- TIPR NEW
var TIPR_DOMAINS = "PCAM"
var TIPR_EVENT_EXCLUDE = "Demo"
-- ToolFail
var TOOLFAIL_FACILITY = "D1D"
var TOOLFAIL_LINK = "http://toolfail.intel.com/reporting.aspx?do=display&fab=D1D&dom=RF3_PFI_DM&id="
var TOOLFAIL_MISCONFIG_TAG = "_Misconfig%"
var TOOLFAIL_PAGERKEY = "RF3_PFI_DM"
-- TWT
var LOCALTWDATASOURCE = "D1D_PROD_TESTWAFER"
var LOCALTWSERVER = "\\RF3PAP435N1\HKLM\SOFTWARE\Intel\TWServer\2.0\Tool_Config"