-- General
var DASHBOARD_PERSIST_DATA = "T:\Dashboard\Data"
var LOCALMARSDATASOURCE = "D1D_PROD_MARS"
var VFGOLDMARSDATASOURCE = "D1D_PROD_MARS"
var MAO_FACILITY = "RA3"
-- Monitor Email
var PCAM_MONITOR_EMAIL = "d1dait@intel.com, d1c.ait@intel.com"
var ONCALL_SUPPORT_EMAIL = "ltd_aog_ci_sc@intel.com"
var CUDESEG_MONITOR_EMAIL = "patrick.e.narvaez@intel.com, d1c.ait@intel.com"
var E3_MONITOR_EMAIL = "wenjie1.jiang@intel.com, heather.marley@intel.com, danielle.m.braun@intel.com, lori.gates@intel.com, d1c.ait@intel.com"
var E3_ADDL_CONTACT_EMAIL = "theodore.stevenson@intel.com"
var E3DEV_MONITOR_EMAIL = "ravi.s.khairate@intel.com, sharon.quan@intel.com, wenjie1.jiang@intel.com, heather.marley@intel.com, kimberly.j.dejong@intel.com"
var E3_VF_STATS_MONITOR_EMAIL = "chris.sluder@intel.com, willo.roe@intel.com"
var SC_MONITOR_EMAIL = "LTDAutomationStationControllers@intel.com, ltd_aog_ci_sc@intel.com, patrick.e.narvaez@intel.com"
var WIP_MONITOR_EMAIL = "d1c_wip@intel.com, d1dait@intel.com"
-- Barnum
var BARNUM_CATALOG = "Barnum"
var BARNUM_DOMAIN1 = "AIT"
var BARNUM_DOMAIN2 = "SPC"
var BARNUM_FACILITY = "D1D"
var BARNUM_LINK = "http://rf3-auto.rf3prod.mfg.intel.com/Barnum/default.asp?do=display&fab=D1D&grp=AIT&id="
var BARNUM_SQL_NODE = "rf3pdb115misql.rf3prod.mfg.intel.com\SQL05"
var BARNUM_RESOURCE_PENDING_FIRST_NAME = "Resource Pending"
var BARNUM_CONV = "Conversion - Process, Conversion - Contaminent"
var BARNUM_DEMO = "Demo - Multiple Tools, Demo - Single Tool"
var BARNUM_INSTALL = "Install - First of a Kind, Install - Second of a Kind, Install - Virtual Winclient, Tool - New Install"
var BARNUM_RELO = "Relocation - Bay, Relocation - Building/Site"
-- BarnumSN
var BARNUMSN_CATALOG = "HelpDesk_30000"
var BARNUMSN_LINK = "http://rf3pvxsn01.rf3prod.mfg.intel.com:8081/nav_to.do?uri=u_barnum_request.do?sys_id="
var D1CBARNUMSN_LINK = "http://rf3pvxsn01.rf3prod.mfg.intel.com:8081/nav_to.do?uri=u_d1c_ait.do?sys_id="
var BARNUMSN_SQL_NODE = "rf3pdb314sn.rf3prod.mfg.intel.com"
var BARNUMSN_TABLE = "d1d_ait_barnum_ticket_summary"
var BARNUMSN_TABLE_D1C = "d1c_ait_barnum_ticket_summary"
var D1DSRFILEFILTER = "@{DASHBOARD_LOCAL_WEB}\PCAM\Output\BarnumSN_Metrics_Current_Queue_Summary.csv"
var VFSRFILEFILTER = "@{DASHBOARD_LOCAL_WEB}\PCAM\Output\ISMP_Request_Query_All.htm"
var REQUEST_NAME = "BarnumSN"
var SRSITE = "%{D1D_CSV}"
-- E3
var LOCALE3DATASOURCE = "D1D_PROD_E3"
var COLLECTION_EXCLUDE = "NA"
var COLLECTION_INCLUDE = "P1270%_CE_%,P1271%_CE_%,P1272%_CE_%, P1273%_CE_%"
var E3_GOLDTOOL_MOVED_INCLUDE = "*"
var SDK_INSTANCE_EXCLUDE = "DEMO*, SST422"
-- FSUI
var FSUISQLID = "FSUIHistoryReader"
var FSUISQLPW = "FSUIHR_mxAo9Ghz"
var FSUISQLNODE = "rf3pDB416SQL01\sql01"
-- MCCB
var MCCBSITE = "D1C"
var MCCBSITE2 = "None"
var MCCBSITEFILTER = "D1C, F24, F28, OSA"
var MCCBCHANGE = "D1CChange"
var MCCBCOMPLETEDBY = "D1CCompletedBy"
var MCCBCOMPLETEDON = "D1CCompletedOn"
var MCCBOWNEDBY = "D1CCompletedBy"
var MCCBCOMMENT = "[D1C Local Comments]"
var MCCBDAYS = "D1CDaysToDone"
var MCCBSENDINGSITE = "D1C"
var MCCBAREAEXCLUDE = "NA"
var MCCBPROCESSEXCLUDE = ""
var SUPPORTSITEVIEW = "D1C"
var AFOMCCBSTATUS = "Not Supported"
var D1CMCCBSTATUS = "Active%, Pending%, ActiveHold%, Proliferation%"
var D1DMCCBSTATUS = "Not Supported"
var F11xMCCBSTATUS = "Not Supported"
var F24MCCBSTATUS = "Not Supported"
var F28MCCBSTATUS = "Not Supported"
var F68MCCBSTATUS = "Not Supported"
var OSAMCCBSTATUS = "Not Supported"
var SUPPORTSITEVIEWC4SORT = "D1C"
var AFOC4SORTMCCBSTATUS = "Not Supported"
var D1CC4SORTMCCBSTATUS = "Active%, Pending%, ActiveHold%, Proliferation%"
var D1DC4SORTMCCBSTATUS = "Not Supported"
var F11xC4SORTMCCBSTATUS = "Not Supported"
var F24C4SORTMCCBSTATUS = "Not Supported"
var F28C4SORTMCCBSTATUS = "Not Supported"
var F68C4SORTMCCBSTATUS = "Not Supported"
var OSAC4SORTMCCBSTATUS = "Not Supported"
var D1CTIPRFILEFILTER = "@{DASHBOARD_LOCAL_WEB}\PCAM\Output\TIPR_Query_Install.csv"
var D1DTIPRFILEFILTER = "@{DASHBOARD_LOCAL_WEB}\PCAM\Output\TIPR_Query_Install.csv"
var F24TIPRFILEFILTER = "D:\Dashboard\Data\PCAM\TIPR_Metrics_PAS.htm"
var F32TIPRFILEFILTER = "D:\Dashboard\Web\PFI\Output\TIPR_Metrics_PAS.htm"
var DEFMETFSGAREA = "Defect Metro, Fab Support Group, DefMet, FSG, DefectMetro, DM, WH"
var DIFFIMPAREA = "Diffusion, Implant, EPI, DI, IM"
var ETCHAREA = "Etch%, ET, Etch - Dry, Etch - Wet"
var LITHOAREA = "Litho, Lithography, LI"
var PLANARAREA = "Inline - ETEST, Planar, PL"
var TFAREA = "EqpMetro, ThinFilms, TFMet, Thin Films%, TF, TM"
var C4SORTAREA = "C4, Sort, ST"
var WIPAREA = "ASOM%, WIP"
var TIPRSITE = "%{D1D_CSV}"
-- MES300
var MES300_ENTITY_EXCLUDE = "PLB_HEAD*,HEAD*, *MONGO*, ZZ*, LPM*, OVP*, PRG*, OVI*, OVN*, SBT*, CAM*, VFQ*, AFQ*, AFW*, ARM*, BAG*, DAT*, DFW*, FMT*, NANO*, RIN*, RIT*, SNK*, VFH*"
var MES300_FA_EXCLUDE = "Automation, AFO*, Bulk Chemical Delivery, C4, FBE, OTHER, LIWS, PC, DieSort, DiePrep"
var MES300_ENTITY_TYPE_EXCLUDE = "ProbeCard, MotherBoard, TestHead"
var MES300_SITE_EXCLUDE = "AFO"
var MES300_CUDESEG_ENTITY_EXCLUDE = "DOR*, LPM*, *MONGO*, VDUM*, STCX*, ZDK*, ZSK*, ZBS*, STC*, DDUM*"
var MES300_CUDESEG_FA_EXCLUDE = "Automation"
var CUDESEG_SOFTPINIGNORETOOLS = "DRT*, PRT*"
var PURGE_CONTACT = "Donavon Miller and Integration"
var PURGE_EXCLUDE_PROCESS = "121%, 126%, XXRP%, RP%"
var MES300_SITE_SPECIFIC_QUERY = "(Site like '${SITE1}' and (NOT IsInList(EquipLocation, '${SITE1_BAY}'))) OR (Site like '${SITE2}' and (NOT IsInList(EquipLocation, '${SITE2_BAY}'))) OR (Site like 'RB1' and (NOT IsInList(EquipLocation, 'STRING, 10, 11, 12, 14')))"
var MES300_SITE1 = "D1X"
var MES300_SITE1_BAY = "600W,600E,601W,601E,602W,602E,603W,603E,604W,604E,605W,605E,606,606A,606B,606C,607W,607E,608W,608E,609W,609E,609A,610W,610E,611W,611E,612E,612W,613W,613E,614W,614E,400W,400E,400B,400AW,400AE,401W,401E,402W,402E,403W,403E,404A,404B,404C,405W,405E,407A,407B,407W,407E,408W,408E,409W,409E,410W,411E,411W,412E,412W"
var MES300_SITE2 = "D1D"
var MES300_SITE2_BAY = "2,2A,2B,ADL,100,101,101E,102,102E,103,104,104E,106,108,109,109A,109E,110,111,112,112E,113,113E,114,115,116,116A,116E,117,200,201,201A,202,203,203A,204,204E,207,208,209,209A,210,210E,211,211A,212,212E,213,213E,214,215,215E,216,217"
var OWD_EXCLUDE_LIST = "4767, 9681, 9683, 119116, 119117, 119222, 119223, 121628, 121629, 121630, 121631, 122502, 122503, 119375, 119376, 119368, 115815, 115817, 115819, 115821, 122141, 122142, 122143, 122144, 122149, 122150, 122151, 122152, 122153, 125582"
var OWD_PROCESS_EXCLUDE_LIST = "1264.0, 1266.0, 1268.0, 1269.0"
-- SC
var TOOLPOST = "H"
var POST = "U"
var NTSCCCServer = "\\rf3pwb100n1\d$\rf3-auto\NTSCConfig_1.7.3.2\log\ScCentralConfigLog*.xml, \\rf3pwb100n2\d$\rf3-auto\NTSCConfig_1.7.3.2\log\ScCentralConfigLog*.xml"
var NTSCCCHistoryExcludeList = "(AFP%, (FBE%, (C4%, (ASP%"
var SCNETSQLID = "uber"
var SCNETSQLPW = "h6wRu5Up"
var SCNETSQLNODE = "RF3PDB416SQL01\SQL01"
var WINCLIENT_EXCLUDE_LIST = "R4PCCC*, R3PCMDC*, R2PCC*, R2PHPCC*,RA4CMD*,R2P6*,R2P7*,R2P8*"
var WINCLIENT_NODE_LIST = "R*P*U, RA4*"
var WINCLIENT_REBOOT_EXCLUDE = "RF3PXPYASMURLN3, *WXP*, *WINC*, RF3PAPMURL, *M, *EPX02*"
var DCSLOTCONFIG_LIST = "*CAR*, *OXS*, *OXT*"
var DCSLOTCONFIG_EXCLUDE_LIST = "*OXS427*"
var MAXCHAMBERDISCONNECT_LIST = "*GST*, *EST*, *NST*, *SST*, *KST*, *QST*"
var MAXCHAMBERDISCONNECT_EXCLUDE_LIST = "None"
var PLASMACLEAN_LIST = "*HME*"
var PLASMACLEAN_EXCLUDE_LIST = "None"
var TOOLDATA_LIST = "*CVD*,*LKL*,*WDP*"
var TOOLDATA_EXCLUDE_LIST = "None"
var WAFERCOUNTER_LIST = "*SLM*"
var WAFERCOUNTER_EXCLUDE_LIST = "None"
-- TIPR
var Fab1 = "D1D"
var Fab1Pre = "R3P"
var Fab2Pre = "R4P"
var TIPRID = "DSI"
var TIPRPW = "DSI"
var TIPRSQLNODE = "rf3pdb415sql03\sql03"
var D1C_TIPR_LINK = "http://rf2-auto.rf2prod.mfg.intel.com/tipr/AIT.asp?FA=All&EntityType=All&Entity="
var D1D_TIPR_LINK = "http://rf3-auto.rf3prod.mfg.intel.com/tipr/AIT.asp?FA=All&EntityType=All&Entity="
var F24_TIPR_LINK = "http://f24-auto.f24prod.mfg.intel.com/tipr/AIT.asp?FA=All&EntityType=All&Entity="
var F32_TIPR_LINK = "http://f32-auto.f32prod.mfg.intel.com/tipr/AIT.asp?FA=All&EntityType=All&Entity="
var TIPR_BUILDING_EXCLUDE = "RA4"
var TIPR_ENTITY_EXCLUDE = "NA"
var TIPRPROCESS = "%"
var EXCLUDETYPE = "NA"
var INCLUDETYPE = "Install"
-- ToolFail
var TOOLFAIL_FACILITY = "D1D"
var TOOLFAIL_LINK = "http://toolfail.intel.com/reporting.aspx?do=display&fab=D1D&dom=RF3_PFI_DM&id="
var TOOLFAIL_MISCONFIG_TAG = "_Misconfig%"
var TOOLFAIL_PAGERKEY = "RF3_PFI_DM"
-- TWT
var LOCALTWDATASOURCE = "D1D_PROD_TESTWAFER"
var LOCALTWSERVER = "\\RF3PAP130N1\HKLM\SOFTWARE\Intel\TWServer\2.0\Tool_Config"